# Generated by Django 4.1.7 on 2023-03-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
